=== EricMunozFernandez/JEMS/XML/DTD_Jugador_Equipo_Dueño.dtd
<!ELEMENT equipos (equipo)+>
<!ELEMENT equipo (nombre, nacionalidad, presupuesto, puntuacion,equipos,dueño)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT nacionalidad (#PCDATA)>
	<!ELEMENT presupuesto (#PCDATA)>
	<!ELEMENT puntuacion (#PCDATA)>
	<!ELEMENT jugadores (jugador)+>
		<!ELEMENT jugador (nombre, apellido, nickname, sueldo, nacionalidad, estado, telefono)>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT apellido (#PCDATA)>
			<!ELEMENT nickname (#PCDATA)>
			<!ELEMENT sueldo (#PCDATA)>
			<!ELEMENT nacionalidad (#PCDATA)>
			<!ELEMENT estado (contratado|vacante)>
			<!ELEMENT telefono (#PCDATA)>
			<!ATTLIST jugador cod_jugador CDATA #REQUIRED>
	<!ELEMENT dueño (nombre, apellido, usuario, contraseña, telefono)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT nacionalidad (#PCDATA)>
		<!ELEMENT usuario (#PCDATA)>
		<!ELEMENT contraseña (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
		<!ATTLIST dueño cod_cuenta #CDATA #REQUIRED>
	<!ATTLIST equipo cod_equipo #CDATA #REQUIRED>

=== EricMunozFernandez/JEMS/XML/XML_Jugadores_Equipo_Dueño_BASE.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE DTD_Jornada SYSTEM "DTD_Jugador_Equipo_Dueño.dtd">

		
	<equipos>
		<equipo cod_equipo="">
			<nombre></nombre>
			<nacionalidad></nacionalidad>
			<presupuesto></presupuesto>
			<puntuacion></puntuacion>
		<jugadores>
			<jugador cod_jugador="">
				<nombre></nombre>
				<apellido></apellido>
				<nickname></nickname>
				<sueldo></sueldo>
				<nacionalidad></nacionalidad>
				<estado></estado>
				<telefono></telefono>
			</jugador>
		</jugadores>
		<dueño cod_cuenta="">
			<nombre></nombre>
			<apellido></apellido>
			<usuario></usuario>
			<contraseña></contraseña>
		</dueño>
		</equipo>
	</equipos>
