=== EricMunozFernandez/JEMS/XML/DTD_LIGA.dtd
<!ELEMENT liga (equipo)+>
<!ELEMENT equipo (nombre, puntos)>
	<!ATTLIST equipo cod #CDATA #REQUIRED>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT puntos (#PCDATA)>

=== EricMunozFernandez/JEMS/XML/XMLclasificacionBASE.xml
<?xml version="1.0"  encoding="UTF-8"?> 
<!DOCTYPE DTD_LIGA SYSTEM "DTD_LIGA.dtd">
<liga>
	<equipo>
        <nombre></nombre>
        <puntos>0</puntos>
    </equipo>
    <equipo>
        <nombre></nombre>
        <puntos>0</puntos>
    </equipo>
    <equipo>
        <nombre></nombre>
        <puntos>0</puntos>
    </equipo>
</liga>

=== EricMunozFernandez/JEMS/XML/XML_Clasificacion_BASE.xml
<?xml version="1.0"  encoding="UTF-8"?> 
<!DOCTYPE DTD_LIGA SYSTEM "DTD_LIGA.dtd">
<liga cod="" fecha_inicio="" fecha_fin="" estado_liga="">
	<fecha_actualizacion></fecha_actualizacion>
    <equipos>
        <equipo cod="">
            <nombre></nombre>
            <puntos></puntos>
        </equipo>
        <equipo cod="">
            <nombre></nombre>
            <puntos></puntos>
        </equipo>
        <equipo cod="">
            <nombre></nombre>
            <puntos></puntos>
        </equipo>
    </equipos>
</liga>
