=== EricMunozFernandez/JEMS/Diagramas/DTD_E_Sports.dtd
<!ELEMENT liga (jornadas,equipos,jugadores,dueños)>
	<!ATTLIST liga cod #CDATA #REQUIRED>
	<!ELEMENT jornadas (jornada)>
		<!ELEMENT jornada (partidos)>
			<!ATTLIST jornada cod #CDATA #REQUIRED>
			<!ELEMENT partidos (partido+)>
				<!ELEMENT partido (equipoA, equipoB)>
					<!ATTLIST partido cod #CDATA #REQUIRED>
					<!ELEMENT equipoA (codigoEquipo)>
						<!ELEMENT codigoEquipo (#PCDATA)>
					<!ELEMENT equipoB (codigoEquipo)>
						<!ELEMENT codigoEquipo (#PCDATA)>
	<!ELEMENT equipos (equipo+)>
		<!ELEMENT equipo (nombre,presupuesto,localidad)>
			<!ATTLIST equipo cod #CDATA #REQUIRED>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT presupuesto (#PCDATA)>
			<!ELEMENT localidad (#PCDATA)>
	<!ELEMENT jugadores (jugador+)>
		<!ELEMENT jugador (nombre,apellido,nickname,sueldo,nacionalidad,estado)>
			<!ATTLIST jugador cod #CDATA #REQUIRED>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT apellido (#PCDATA)>
			<!ELEMENT nickname (#PCDATA)>
			<!ELEMENT sueldo (#PCDATA)>
			<!ELEMENT nacionalidad (#PCDATA)>
			<!ELEMENT estado (#PCDATA)>
	<!ELEMENT dueños (dueño+)>
		<!ELEMENT dueño (nombre,apellido)>
			<!ATTLIST dueño cod #CDATA #REQUIRED>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT nombre (#PCDATA)>

=== EricMunozFernandez/JEMS/XML/XMLgeneral.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE DTD_E_Sports SYSTEM "DTD_E_Sports.dtd">
<liga cod="">
	<jornadas>
		<jornada cod="" fecha="">
			<fecha></fecha>
			<partidos>
				<partido cod="">
					<equipoA>
						<codigoEquipo></codigoEquipo>
					</equipoA>
					<equipoB>
						<codigoEquipo></codigoEquipo>
					</equipoB>
				</partido>
			</partidos>
		</jornada>
	</jornadas>
	<equipos>
		<equipo cod="">
			<nombre></nombre>
			<presupuesto></presupuesto>
			<localidad></localidad>
		</equipo>
	</equipos>
	<jugadores>
		<jugador cod="">
			<nombre></nombre>
			<apellido></apellido>
			<nickname></nickname>
			<sueldo></sueldo>
			<nacionalidad></nacionalidad>
			<estado></estado>
		<jugador>
	<jugadores>
	<due単os>
		<due単o cod="">
			<nombre></nombre>
			<apellido></apellido>
		</due単o>
	</due単os>
</liga>
